### PR TITLE
Understand Python Code

### PR DESCRIPTION
**Pull request by saulshanabrook**
The goal of this PR is to explore how we can understand Python itself in metadsl. If this works, it will bring it closer to static analysis tools, like Numba, or alternative Python compilers like PyPy.

The general proposed architecture is documented in the docstring on the new module, but is generally:

1. Start with Bytecode
2. Build a SSA representation from the bytecode
3. Convert from SSA form into dataflow form

This is a nice parallel to the existing transformations to produce LLVM, which happens in the inverse form, starting with a dataflow form, and then moving to the LLVM SSA, before converting to LLVM.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
The first stage of this is turning the bytecode into a data structure that closer mirrors it's semantics instead of its in memory/on disk representation.

I am working on this incrementally, starting by parsing each attribute of the `Code` object, and then will work on seeing if they can combined or re-organized more succinctly.

**Comment by mattip** [comment]
Any idea how flexible this will be? Will it hit things like https://github.com/numba/numba/issues/7562 when using different versions of the bytecode?

**Comment by saulshanabrook** [comment]
@mattip thanks for the pointer to that issue. I hadn't seen Numba's new `objmode` context manager, that's a nice addition!

In terms of supporting multiple Python versions, the general plan is to support something like 3.7-3.10 currently. 

With regards to feature parity of Numba and using object mode, that is still a long ways off, and I haven't thought at all about the UX for this sort of compiler suggestion.

The goal though is to architect this in a way where you start with 100% Python language coverage and accuracy and incrementally add support for lowering/understanding different Python constructs into a dataflow form. From there, you could again incrementally lower to an LLVM form to achieve something similar to Numba.

**Comment by saulshanabrook** [comment]
I split off the first bit of this work into a separate package: https://github.com/metadsl/python-code-data

It does not depend on metadsl and is only about translating python code objects to an easier representation to work with. I am closing this for now, since most of the changes were integrated there, and will re-open when I have bandwidth to build metadsl translations on top of it.

**Comment by saulshanabrook** [comment]
Closing now that we have [python-code-data](https://python-code-data.readthedocs.io/en/latest/).

I moved the Python 3.7 and CI support to this new PR https://github.com/metadsl/metadsl/pull/144. I don't think we want to maintain the local conda env support.

**Pull request closed without merging**
